
spring:
  profiles:
    active: local
  batch:
    job:
      enabled: true
      names: batchJob

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
      username: springbatch
      password: springbatch
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties: 
      hibernate:
       format_sql: true
       use_sql_comments: true